### ISSUE TITLE
Bad formatting in GPLv2

### ISSUE THREAD

**Issue by joshkel** [IQAndreas/markdown-licenses#10]
At the bottom, it has this:

    `show w' and `show c`

which shows up like this:

> `show w' and `show c`

It should be this:

    `show w` and `show c`

so that it will show up like this:

> `show w` and `show c`

**Comment by dodekeract** [comment]
Y u no pull request?

**Comment by joshkel** [comment]
I had some reason at the time. I'm not sure now.

Oh well. I opened PR #11.

**Comment by IQAndreas** [comment]
Fixed in 66202b51f3cfa74d8008e395f89d403a7f5a27ed
